angular.module('app', [
  'ngSanitize',
  'ngTouch',
  // 'ngAnimate',
  'angular-cache',
  'ui.router',
  'ui.bootstrap',
  'cgBusy',
  'toastr',
  'xeditable',
  'pascalprecht.translate',
  'ncy-angular-breadcrumb',
  'ngTable',
  'ngMessages',
  'ui.toggle',
  'ngTagsInput',
  'ui.tree',
  'ui.tab.scroll',
  'ngMap',
  'chart.js',
  'luegg.directives',
  'dndLists',
  'highcharts-ng',
  'uiCropper',
  'naif.base64',
  'mentio', ,
  'compile',
  'ngAside',
  'gridstack-angular',
  'ngFileUpload',
  'ng-mfb',
]);

Number.MAX_SAFE_JAVA_INTEGER = 2147483647;
